version: 0.0
os: linux
files:
  -files:
    - source: /
      destination: /var/www/html
  hooks:
    AfterInstall:
      - location: scripts/intall_nginx.sh
        timeout: 300
        runas: root
    ApplicationStart:
      - location: scripts/start_nginx.sh
        timeout: 300
        runas: root        
    